version: '3'
services: 
  jupyter:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/home/jovyan/
    ports:
      - "8888:8888"
    container_name: jupyter01
  db:
    image: postgres
    restart: always
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
volumes: 
  pgdata: